### ISSUE TITLE
100% unclassified reads - 0 classified

### ISSUE THREAD

**Issue by SziKayLeung** [nanoporetech/pychopper#12]
Hello, 

While the pychopper ran successfully (with conda installation), all the reads from my MinION run was unclassified (from the stats.output) : 
+       -       unclassified
0       0       2122012

I had created my cDNA using the SMARTer cDNA Synthesis kit, and thus had adjusted the primer.fasta file accordingly to the 5' and 3' primers:
>cDNA|1
AAGCAGTGGTATCAACGCAGAGTACATGGG
>cDNA|2
GTACTCTGCGTTGATACCACTGCTT

But when I grepped the input fastq file, there were occurrences where the primers were matched at both ends of the read (find attached). 
I was under the impression that Pychopper looks for the specified primers at the two ends, and if it finds both in the directions indicated at both ends, it is considered classified. So in this case, both reads in my example should be considered classified?

The command I used was:
dna_classifier.py -b $REFERENCE/nanopore.primer.fasta -r $1.report.pdf -u $1.unclassified.fastq -S $1.stats.output -A $1.scores.output $RAWDATA/$1.merged.fastq $1.FL.fastq

Any guidance on this would be greatly appreciated - Thank you!
[match_primer.fastq.docx](https://github.com/nanoporetech/pychopper/files/3287340/match_primer.fastq.docx)

**Comment by bsipos** [comment]
It seems that cDNA|2 is a sub-sequence of the reverse complement of cDNA|1! Under these circumstances it would be possible to detect if the read is full length, but it is impossible to figure out the strand so pychopper will not classify them.

**Comment by SziKayLeung** [comment]
Thank you for your reply and for clarifying about the need for strand direction. 

Perhaps more useful, below are the sequences that are based on the cDNA primers+polyA/T for differentiation:
Adapter('SMARTer_cDNA_Synthesis_plus_strand

                    start_sequence=('primer_5p', 'CAGTGGTATCAACGCAGAGTACATGGG'),
                    end_sequence=('primer_3p', 'AAAAAAAAGTACTCTGCGTTGATAC')),
            Adapter('SMARTer_cDNA_Synthesis_minus_strand',
                    start_sequence=('primer_5p', 'ATCAACGCAGAGTACTTTTTTTT'),
                    end_sequence=('primer_3p', 'CCCCATGTACTCTGCGTTGA'))]

**Comment by bsipos** [comment]
I am afraid there is now way to orient the reads without adding unique sequences to the two primers.
You could still decide if they are full length based on the alignment scores written out by specifying -A.
