### ISSUE TITLE
error in pychopper run

### ISSUE THREAD

**Issue by ljw90607** [nanoporetech/pychopper#16]
Hi,

I am having a trouble running pychopper
I have used the script as below;
`cdna_classifier.py -b /reference/cdna_barcodes.fas -r pychopper_report.pdf -u unclassified.fastq sample.fastq pychopper.fastq
`
and here is what I got as an error;

> Traceback (most recent call last):
>   File "/usr/local/bin/cdna_classifier.py", line 7, in <module>
>     exec(compile(f.read(), __file__, 'exec'))
>   File "/appl/pychopper/pychopper/scripts/cdna_classifier.py", line 97, in <module>
>     barcodes, aln_params=ALIGN_PARAMS, target_length=args.t, percentile=args.s, nr_samples=args.n, heu=args.x)
> TypeError: calculate_score_cutoffs() got an unexpected keyword argument 'heu'

I am not sure how I can fix this issue. If you could help me with this I would really appreciate it!

Thank you!

**Comment by bsipos** [comment]
Which version of pychopper are you using?

**Comment by ljw90607** [comment]
@bsipos 

I have just downloaded the newest version and tried the script as shown above.

Thank you for your answer!

**Comment by bsipos** [comment]
Did you download the latest release? If yes, could you clone or install from the repository?

**Comment by ljw90607** [comment]
Dear @bsipos 

Yes I just downloaded the latest release from the repository again and still prints the same error.

Jungwoo

**Comment by bsipos** [comment]
Both the latest release (v0.6.1) and the master is working for me. What is your python version?
Also, you could try to install it from [bioconda](https://bioconda.github.io/recipes/pychopper/README.html).
