### ISSUE TITLE
Error Sequence file - is empty or misformatted when using pHMM backend

### ISSUE THREAD

**Issue by defendant602** [nanoporetech/pychopper#20]
I am using pychopper v2.0.3 to classify a ONT cDNA data and I get an error when using the default pHMM backend, but the error disappears when I use edlib backend.

The error log is

`Configurations to consider: "+:SSP,-VNP|-:VNP,-SSP"
Total fastq records in input file: 11895884
Tuning the cutoff parameter (q) on 9964 sampled reads (0.1%).
Optimizing over 30 cutoff values.
  0%|          | 0/30 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/export/pipeline/RNASeq/Software/Pychopper2/v2.0.3/bin/cdna_classifier.py", line 264, in <module>
    for read, (segments, hits, usable_len) in backend(batch, executor, qv, max(1000, int((len(read_sample)) / args.t))):
  File "/export/pipeline/RNASeq/Software/Pychopper2/v2.0.3/pychopper/chopper.py", line 102, in chopper_phmm

Error: 
Error: 
Error: 
Error: Sequence file - is empty or misformatted
Sequence file - is empty or misformatted`

My command is 

`cdna_classifier.py -u unclassified.fa -S statistics.txt -A aln_hits.bed P1_PAD47907_26730.pass.filter.fastq full_length_output.fq`

and the first three fastq records in input fastq file is 

`@f70d4e23-00b9-4225-917f-1a8cb2e813e0 runid=3e5dd73ec745e35e72895acf1ba6bcb6f343381b read=7 ch=2787 start_time=2019-07-05T09:15:49Z flow_cell_id=PAD47907 protocol_group_id=basecalled sample_id=20190705-YFL027-P1-PAD47907
ATCTCAAGACTAGTATTGTGTCTAAACTATGGCTACAGAGAAATCAGAAATGTCCTCTGATGGTCCAAGTCCTGGATGCTGTCGAGGCAGCCTGCTGTAAAGGCCCCGTGGCTGTAAAAGTGTTCAAAAGACCTCTGAGGATCCTGGGAGCCCTTGCCTCTGGGGAAGACACAGGTCTGGAGAGCTGCACAGGCTCACCACAGATGAGGTTGTGAAAGGGTGTACAGAGTAGAACTGGACACCAGTCGTGCTGGAAGACGCCCGGCGTTTCCCATTCCATAATTCGCAGATGTGGTTTTTCACAGCCAACGACTCTAGCCATCGCCACTACCATCGCAGCCTGCTCAGCCCCGCCTCCTACAGCACCACGGCTGTCGTCAGCAACCCCAGAATTGAGGAGCTCATGGGAGGACCAGGATCTTGCCAAGTGTGGCATCCCATTTGTGCAAAACAGTGTTCTTGCTCTGCCAAACCGTGTTAGCAGCTCAGGAGATGCCCGTGAGCATTCTTATTAAACCCTGCTGTTTCATGCAAAAAAAGTACTCAGCAATGCGTGGCTACTAG
+
"#"""""&&(&&#""#""%#%$")-,'&&&#"#%#"#$##+*1*,&$('(&&)+)')%%%*+0-.&0(,,07133124:::56'(/++-89>720,+(%$$$%$&"$&.*//.--,33)+-18=8/;0-*2/34444(<94;8''),-'$+.)-6(-,,/.*+.(**&$&&##(''*+('&&&+..00,/'17-,)#*,&*+,3/+'++)1+,*(00'.//05'50.(**-14979;:58.0-'#%%"#"%%%*)))1,#'$"'#"#+-,2:,(4<7813&,&:)-2.3:8)/)..=<2*(&&'-19033/,34/.%.195..(-,354695034#'&%,,,%)*/,/298&#$))./)/800001.(*)$#$%&5165*-+/)33:/&%*)5*'&$**#(:3'-$-1,.0/:;':8-42-4++,'&$#$&$%%'+40.,/7,-0+1*68.3'333.5'()"#*-'"%(54'4:3603.(*0'.0/5%-/0*-/++,&#/%&+2(-5*+2'*.(+)*,')368,46/-),(0,79863.)-)##""#(&&&$$'''"$$"##""
@8c6a10e0-24e4-4cf8-a8cc-8e084d3d61f1 runid=3e5dd73ec745e35e72895acf1ba6bcb6f343381b read=7 ch=2708 start_time=2019-07-05T09:15:49Z flow_cell_id=PAD47907 protocol_group_id=basecalled sample_id=20190705-YFL027-P1-PAD47907
ATCAATATACACCATTCAATTGTATTACTAAACAGTAAATATCAACCTGAAATACTTTCTACGTTTTGTGGTCTGTGATGAAGGACCTGGCACATTACGTGGATGTCATGATCTTCAGGTGGCCCGCCAGGTGCTCAGGAGAACGTGTCTTCAACTTCTCCTTCACTTTGCCAATGCCTCTGAGAACCAGGCCGGGTCTTGGTCAAAAGAATTTCGGCTTGTTTGATATGTTCAATGGCTGCCCAGGCCTTGTCTTCCAAAGTGTTCCCCCAAACTCCTTCAGTTTATCGGTATGCTCTCCAATGTTCAGACCGTCCCAGGGCCGCCTGGGCAGAGGCTGGGCCTTCCAAGGTCATGGCTGACCACAATCAGGTTTAGGAAAGAGCGATGAAGAGCCTCATCACAGTTTGGAGGGGCACCTGGTCTGAGATCTCTCAGAGGCCCATGGCCCCATGTGCTCTGCGTTGATGCCTTAGCCCTTGTGCAACTTC
+
21*/))*'$'#)&##($,+,+$(%*)'(*3*((,%,(,'**.(+'&%&#'*&&"#'()%'&)&,5:*',,713503224&0()*8;=833--,&0&()&8%')2358&)'','+5.%(-+-1/.)(.113:92235+.4.005.,.0.+.=03--4943;=.//'(471)+,)-,.-100/,,&(10557825)6:4-4-9.61-/+*%)&66**)+./8:10)%&,+3.86/$#*&,-.*-)%#',6:00--,52)%&)%%'(/91:<:3.9657<8/37(*.>0,33&$/061000-6,-(4'0*$&'*-;8.6+("+(%(+'+7/0851.(&+,*&'+-.+/23'*%/,0-')'*((%%'*$%)&++&10,-'&1.-/-)*,1.02,+2*&)(001-43&)&+1<,4-(+(+&$#,--.+%$&&'-,.+,/.3()%'(./.%,',))-*&'%("%1-;665/-)))$+&#"%(--&%&$$%#$##%$"
@491632f2-6aca-48f4-bc46-7fd70629abd7 runid=3e5dd73ec745e35e72895acf1ba6bcb6f343381b read=7 ch=2546 start_time=2019-07-05T09:15:49Z flow_cell_id=PAD47907 protocol_group_id=basecalled sample_id=20190705-YFL027-P1-PAD47907
ATAAAAACGTAGCCATAGAAACCTAGTCAATTTGATATTACCACTGTTGCTTAATTTGGTCGGCCTGAGATGGCATCAATTTTAAGTCTGGGAGGACTGCTCATGAGTGGAGACGTCTTCCAGATATGCAGAGTGTATACGGATTGGAAGTTCTGTGGCAGAACGACTCGGTTATCAACTTCCTGGCAGTCGTAGTTCACCGGGTTTGGGTCGTTTGTTTGGGATTGTGTGGATCCAAGCATGAGTCTTCATGGTCAGTATATATTCGTAGCTTCAGTATCATTGGTGCTATGGTTTAACAGTTAATGCAGGGGTTGTTGATTTTAAATTATTATATATAGAATGCGTAGAGAGCAATTATGATAAGGATTGCAGCTGGTAGAATAGTTCAAATGGTTTCCTTCTTGTGCATCTGTTGTTGTATGTGTTAGTTTTTGTTGTTATGTGGCGGATGATGTAGAGGGACTGAGGAGGCTAATTGGGAAAACGGTGTGGTGTGTGATCATGGAATTGTTGAAACAATATTGGGGATGGCGTCTTGGAATGGATTTGAGATGGGTGCATCATGTGCGTTGATGTGCGTGACTTCT
+
*1##$$$%$*#%%$%&($)'$&&$#%()'&,5,(**%'*#&&&(,$..&()'&(/0'%%&'(+1-32)1,%%,*+-,)$)28*)%((),&/8/1628<;:83*.,(+,)(',*303378+.)*+-#$"$'&)()+/#%$'%-#5&5)+((,5010/-&#$&(&&'&/00*&/2%)+4.,12-'&%)'$+00&3$64;/(--*765;7(.2-,,-7<+,5+-0*%0-&.()&)+,<)5/,,.1%$&(#51--2%70<')).-,-/2;643%$)-./&-/-1612;)&$')+04867;2)5-%9423'*&6'//+)-7+08.*05+"+(#(%&*(),:::;699><7,13)*'''&*'(1+*/++2*1-8+3+#&&),*-'))+/85-9;616==525098-('*(-2-0-0122;.;1%2((&&*22/02)109=9,*/;).+)+$.&,&*+.*))*#*%(&/0815,%&0,$((')&(0*0:326+)1&'2'()3310,+*(+(&-/-'#('$('&$&$#$#%&*,.98.&('%$+-'''&'###&(")'''%&,6/1%%&"#&+#$###$&))$"$$$()+,,)'%%$#`

Could you please help me out on this error? Thanks a lot.

**Comment by bsipos** [comment]
Well, it looks like the input fastq is indeed malformed! You are missing the new lines around the "+" separating the sequence and quality lines (or maybe newlines in general). You can use [seqkit sana](https://bioinf.shenwei.me/seqkit/usage/#sana) to recover the usable records. If all records look like this then you are out of luck and will have to re-generate the fastq.

**Comment by defendant602** [comment]
Thank you for your reply, but I think there is a misunderstanding here. I am sure my fastq format is good. It looks malformed just because it is not displayed well in this page. In my unix, it looks like this:

![20190927094257](https://user-images.githubusercontent.com/37471184/65735793-429d3680-e10b-11e9-861d-413fca18a82c.png)

Besides, when I added -m edlib option and run it again, the error disappeared and pychopper completed  successfully. So maybe there are other reasons?

**Comment by bsipos** [comment]
Well, that is a problem. Could you please upload the first 1000 records of the offending file (please check if it enough to reproduce the problem).
Also, how did you install pychopper? If you did not install from conda, what is the versiuon of hmmer on your system?

**Comment by defendant602** [comment]
I tested the pHMM backend using the first 1000 records, and the problem turned up again.

Configurations to consider: "+:SSP,-VNP|-:VNP,-SSP"
Total fastq records in input file: 1000
Tuning the cutoff parameter (q) on 1000 sampled reads (100.0%).
Optimizing over 30 cutoff values.
  0%|          | 0/30 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/export/pipeline/RNASeq/Software/Pychopper2/v2.0.3/bin/cdna_classifier.py", line 264, in <module>
    for read, (segments, hits, usable_len) in backend(batch, executor, qv, max(1000, int((len(read_sample)) / args.t))):
  File "/export/pipeline/RNASeq/Software/Pychopper2/v2.0.3/pychopper/chopper.py", line 102, in chopper_phmm
    for i, hits in enumerate(batch_hits):
  File "/export/pipeline/RNASeq/Software/Pychopper2/v2.0.3/pychopper/hmmer_backend.py", line 36, in find_locations
    for res in pool.map(_find_locations_single, zip(batches, [(phmm_file, E, 1)] * len(batches))):
  File "/export/pipeline/RNASeq/Pythonpackage/concurrent/futures/_base.py", line 641, in result_iterator

Error: Sequence file - is empty or misformatted
    yield fs.pop().result()
  File "/export/pipeline/RNASeq/Pythonpackage/concurrent/futures/_base.py", line 462, in result
    return self.__get_result()
  File "/export/pipeline/RNASeq/Pythonpackage/concurrent/futures/_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
AttributeError: __exit__

I built hmmer from source and installed pychopper using pip. The version of my hmmer is 3.2.
`$nhmmscan -h

 #nhmmscan :: search DNA sequence(s) against a DNA profile database
 #HMMER 3.2 (June 2018); http://hmmer.org/`

The attached file is the first 1000 records of my fastq file.

Thanks.

[head1000.zip](https://github.com/nanoporetech/pychopper/files/3665033/head1000.zip)

**Comment by bsipos** [comment]
Hello!
I have downloaded the dataset and pychopper runs on it without any errors, hence the issue is likely your environment (Python and hmmer version). Please remove the manual hmmer install from your system and install pychopper from bioconda in a fresh conda environment. Let me know if it still fails.

Best,
Botond

**Comment by bsipos** [comment]
On a different not, which protocol was used to generate this data? I have checked the stats and the number of classified reads is quite low, depsite the mean qualities begin decent.

**Comment by martynakgajos** [comment]
I have similar problem:
With version 2.0.0, I am able to run the tool successfully (~40% of reads classified).
I have tried version 2.0.3 and now:
1) I get the error running it with pHMM backend
2) when I add -m edlib option, the error disappears but pychopper completes with 100% of reads not classified.
We used SQK-DCS109 kit.

**Comment by bsipos** [comment]
@martynakgajos Could you please let me know the following: the way you installed pychopper (if not from conda, please first try that), version of basecaller, sequencing protocol, whether you only used reads with mean quality > 7.

Thanks,
Botond

**Comment by martynakgajos** [comment]
I have installed now the pychopper with conda, but the results are: 
1) same for the edlib option,
2) I get the following error using pHMM backend: `/bin/sh: nhmmscan: command not found`

We used standard sequencing protocol for direct cDNA (sequencing kit: SQK-DCS109), reads were basecalled with Guppy 3.2.4 with flags: --qscore_filtering --min_qscore 7.

**Comment by bsipos** [comment]
@martynakgajos Your install still seems to be broken somehow. If you installed using conda make sure that the environment you have installed pychopper is activated.
Did you turn on trimming from the config by any chance (Should be off by default)?
