### ISSUE TITLE
Issue with unclassified reads

### ISSUE THREAD

**Issue by Jordthomas93** [nanoporetech/pychopper#21]
Hi,

Using the PCS109 protocol to sequence cDNA with standard RT primers and barcoded PCR primers. Basecalled, demultiplexed and trimmed using guppy in one step:

`guppy_basecaller -i nanopore/HCV_transient/run1/HCV_293T-300919/Library1_P2E1/20190930_0942_MN29596_FAL13008_40f16fc5/fast5 -s nanopore/HCV_transient/run1/guppy_output/Lib1 --flowcell FLO-MIN106 --barcode_kits SQK-PBK004 --kit SQK-PCS109 --num_callers 6 --cpu_threads_per_caller 10 --qscore_filtering --min_qscore 7 --trim_barcodes`

Concatenated and zipped reads and basic stats for one library is as follows:

Total n:        1665339
Total seq:      1911874852 bp
Avg. seq:       1148.04 bp
Median seq:     1045.00 bp
N 50:           1386 bp
Min seq:        1 bp
Max seq:        13309 bp

Used pyhcopper to get full length reads from this library using this code:

`cdna_classifier.py -r E1E2-1-report.pdf -u E1E2_uncl.fq -w E1E2-rescued.fq E1E2_1_R1.fastq E1E2_1_R1_FL.fq -t 16`

Before classifying it had this warning:

Tuning the cutoff parameter (q) on 9882 sampled reads (0.6%).
Optimizing over 30 cutoff values.
Best cuttoff value is at the edge of the search interval! Using tuned value is not safe! Please pick a q value manually and QC your data!
Best cutoff (q) value is 5.0000 with 13% of the reads classified.

Here is the pdf report for this:

[E1E2-1-report.pdf](https://github.com/nanoporetech/pychopper/files/3698566/E1E2-1-report.pdf)

Is there any reason why the classification is so low? Have i gone wrong somewhere or are most of my reads really not full length? Only Q>7 are used as these are filtered during basecalling?

Thanks in advance for any help on this.

**Comment by bsipos** [comment]
Please turn off trimming! It removes the primers needed by pychopper.

**Comment by bsipos** [comment]
Well, it removes those as well.

**Comment by Jordthomas93** [comment]
Fair enough! Will redo the basecalling without trimming, thanks for the help
