### ISSUE TITLE
less full length reads detected than with the v0.5.0 version

### ISSUE THREAD

**Issue by HegedusB** [nanoporetech/pychopper#22]
Dear Sipos,
I tried out the newest Pychopper version (v2.0.3) and I get much less full length reads than with the older version (v0.5.0) on a similar dataset. How is it possible? Which parameter should I fine tune? The –q ? When I manually change the –q value, (-q 7) the program ignored it and used the autotuned number. Is there any other parameter which I should change? 
Thanks for any help!

**Comment by ksahlin** [comment]
Hi!

How much is much less? Also, do you have reason to believe that the new version filters reads that shouldn't be filtered? That is, did you observe reads that seemed valid full-length reads in the previous version but were absent from the output in the newer version?

Best,
Kristoffer

**Comment by ksahlin** [comment]
The reason I ask these questions is that it's expected that the newer version will yield slightly less full-length reads than the older version because the newer version is more strict in its default parameters.

 (I observed around 70%-90% of reads compared to  the older version)

**Comment by HegedusB** [comment]
Only ~10% of the reads remained. Which was shocking.

**Comment by bsipos** [comment]
I would need a couple of questions to be answered to clarify this issue:
- Did you run pychopper on the pass (Q > 7) reads only?
- What was the protocol used to generate this dataset? DCS109 by any chance?
- Could you run the old version on the exactly same (new) dataset?
- Could you attach the PDf report for the old and the new version?

A classification rate of 10% indicates that there might be issues with the quality of the dataset.
In order to fix -q, you must set -Y to 0. However, since pychopper picks the -q which maximizes the number of classified reads manual tuning might not be that useful.

Best,
Botond Sipos

**Comment by HegedusB** [comment]
Thanks for the quick answer! 
- yes, I only used the pass reads (Q > 7)
- I used the lexogen teloprime v2 protocol (full length cDNA Amplification kit), I barcoded the samples with ONT Native barcodes, and for sequencing I followed the DCS109 protocol
(I used lexogen teloprime specific primers)
A have run the old and new pychopper on a same dataset (subsample of the original), and attached the PDF report file.

Used command:
# New (v2.0.3):
cdna_classifier.py -b ../cdna_barcodes_teloprime_v01.fas -r report.pdf -S report.stats -A report.scores -u report_unclass.fastq -t 40 -p ../barcode01_all.fastq report_full_length.fastq

# Old (v0.5.0)
cdna_classifier.py -b ../cdna_barcodes_teloprime_v01.fas -r report.pdf -S report.scores -A report.scores -u report_unclass.fastq ../barcode01_all.fastq report_full_length.fastq

[report_v2.0.3.pdf](https://github.com/nanoporetech/pychopper/files/3814357/report_v2.0.3.pdf)
[report_v0.5.0.pdf](https://github.com/nanoporetech/pychopper/files/3814398/report_v0.5.0.pdf)

Thanks for any help!

**Comment by bsipos** [comment]
Please specify -m edlib for v2 with custom primers!

Botond

**Comment by HegedusB** [comment]
O! I see now!
Can you please help me, how to make a configuration file from the primer sequences. It is not trivial for me.
These primers worked for me with the v0.5.0:

>cDNA|1
TGGATTGATATGTAATACGACTCACTATAG 
>cDNA|2
AAAAAAAAAAAAAAAAAACGCCTGAGA

**Comment by bsipos** [comment]
You have to rename the primers like

```
>SSP
TGGATTGATATGTAATACGACTCACTATAG
>VNP
reverse complement of AAAAAAAAAAAAAAAAAACGCCTGAGA

```
Botond

**Comment by HegedusB** [comment]
Thank a lot Botond! Now everything is forking fine!
