### ISSUE TITLE
questions about output full-length reads

### ISSUE THREAD

**Issue by defendant602** [nanoporetech/pychopper#23]
Hi, I used pychopper(v2.0.3) to classify a PCR-cDNA dataset and I got a full-length ratio of 84.36%. The  results are good but I notice that some full length reads are from the same original read in the input file, for example :

These two full-length reads "2420:3634|00b4c0fe-97c6-4510-8b8f-df9cd674568c" and "77:2289|00b4c0fe-97c6-4510-8b8f-df9cd674568c" are from the same original read "00b4c0fe-97c6-4510-8b8f-df9cd674568c" .

Why would this happen ? I assume one original read would yield only one full-length read. And what do the numbers mean ahead of the reads id? Do they mean the start and end position in the original read?

**Comment by bsipos** [comment]
These reads can arise if an open pore is missed, so two reads get fused together. Pycopper v2 is able to deal with an arbitrary number of fused reads, though in my experience most have two "subreads" and their frequency is pretty low in general.
Yes, the numbers before the IDs are the start and end positions on the original reads after trimming.
