### ISSUE TITLE
Score file of pychopper v2

### ISSUE THREAD

**Issue by bressin** [nanoporetech/pychopper#25]
Hi,
thank you for the update, the rescue of fusion/chimeric reads is great.
However, I have problems to understand the new score file (-A scores_output     Write alignment scores to this BED file.) due to the lack of a header or information in the README.

I also have a problem to understand SPP,-VNP ?

Thank you in advance,
Annkatrin

**Comment by bsipos** [comment]
The fields in the BED file are: read id, reference start, reference end, primer name, alignment quality, alignment strand. SSP is the strand switching primer, -VNP is the reverse complement of the VN primer.
