### ISSUE TITLE
Read truncation and mis-orientation

### ISSUE THREAD

**Issue by GenomeRIK** [nanoporetech/pychopper#26]
Hello,

I noticed an issue when running Pychopper on Nanopore cDNA reads (LSK109) generated from cDNA libraries prepared with the Teloprime kit. The issue is that there are significant number of reads which are being truncated and mis-oriented due to what seems like erroneous identification of primers from Pychopper. 

The input primer/adapter sequences are:
>SSP
TGGATTGATATGTAATACGACTCACTATAG
>VNP
TCTCAGGCGTTTTTTTTTTTTTTTTTT

For example this is a read from Guppy HAC basecalling fastq file:
@93972a90-a05e-49a2-b236-f0c97e9360d6 runid=42615ab958d88032e437976a4c7d836ed71976b3 sampleid=RK_CH2222 read=21915 ch=387 start_time=2019-12-04T00:31:34Z
CAGTGTACTTCGTTCGGTTACGTATTGCT**TGGATTGATATAGTAATACGACTCACTATAG**AGTGTGAGGCGAGCCGTCGAGCGGAGCAGGTCGCTGGTGCGCACCGTGCAGCCGTTAGCTCCACCGCACCCCGCAGCCGGGCCGAGCCACCATGGCTGATCAACTGACAGAAGAGCAGATTGCAGAATTCAAAAGAAGCTTTTTCACTATTTGACAAGGATGGTGATGGTACTATAACTACAAAGGAGTTGGGGACTGTGATGAGATCACTTGGTCAGAACCCCACAGAAGCAGAATTACAGGACATGATCAATGAAGTAGACGCTGATGGCAATGGCACAATTGACTTCCCAGAGTTTCTGACAATGATATGTAAGAAAAATGAAAAAGATACAGATAGCGAAGAAGAAATTAGAGAAGCGTTCCGTGTGTTTGACAAGGATAATTAATGGTTACATTAGTGCTGCAGAACTTCGTCATGTGATGACAAATCTTGGGGAGAAGCTAACAACAGATGAAGAAGTTGATGAAATGATTAGGAAGCAGACATTGATGGTGATGGTCAAGTAAACTATGAAGAGTTTATTGCAAATGACAGCGAAGTAGAAGACGTTGCAGAATGTGTTAAATTTCTTGTACAAAATTGTTTATTTGCCTTTTCTCTGCTGTACTTATCATGAGGTTTCACTTACTGTCAAAAGAATATGTATAGTAATTAGAAGGCCATTCCTCCATGTTTTTCTCCTTTATCTTACTGCCATTGTTACGATTTTTGGAAAATTGATCATGCTCAAATGTTGCATGTGGCTTACTCTGGATATTTAAGCCCTTCTGCACATCAATGTTAGATGGAGGTTGGTAAAATGAGGAACATCTGGATTGTTTAAAATAACTTTCTCTAGAAGACTTAGGTATGACTAGTGTAAGCAAGTTACGTAAAGTAAGTTAGGTTTTACCATGCACATTAGCAGTTCCTTATTTAAAGCGAGATGCTGACCTAGTTTTCCAGTGCGTAAGTTTATTCTGCTTTTTGATGATTGAGTTAAGGTTACAGTTGACTGCAGGACAAGCGATGTGAATAAGCATATGTATTTAATGCACTGCAAAAAGTATTCTGACTTACTTCATAGTAACTTGTTTGTGGCCATACCTGTAACATGTTGTTGAAATGTAAGGTCTTAACATTGTGGACGATTGACAGTCAACAATATGAATCTTAAAGTTGCACTAATGCAAAACGGTGTATTATCCAGGTACTCGTACACAATTTTTGTACTGCTGGTCACCTTTACTGAAAACCTTTTCTCCTCTTGTTACTATGCTTTTTAAACTTTGTTTAGCCACTTATTTCAAAAAAAAAAATCTGCTTATGGCACGATTTGCCTCAAATCCATTCAGATTGTATATTGTTTTCCAATAAAAATTACAATTTACCCATACTGTTCAATGTATCCTTGAATTATTTACAGGATTTGTTCAATACAGTTGCTGCTCTGTGTTTTCCAGTATGTAGCAGTTTGATTTGCTTATGCGATGGATTGGCTGTCTTAAGAGCTTGGAAGGTGAAATCTTAGACCGTAAACTCTGGCCCTTTATTAGTATTGTTGACTTGAAGAAGCTTTCTTTAGTAGTTTAAATGTATTTTACTGATCTTGTGGTAGACTTGGTGTAATATACTTACCATAGTGACTGGCTATGCCCACTATCTGTGGTATTGTGAACTGGATGTTGACCTAGTTCCAATAGTTGACCTAAAATTAAAATTCCTTGTTCAGACAACT**AAAAAAAAAAAAAAAAAAAACGCCTGAGA**AGCAATACGTA
+
*#&''.-67959?1<',584=A>@:64222454DF?;7+$$)$./06;BEBLDECFA;A<*72134),3+,-AFE@?:76,/29+1%',:EEDEDA@B:7:78:93=834556-==9<?C7;;GG337654$$,)%).&+,225><@A8@0579=?GMHCH335594989<9<<8::<455DBIB;;24<CC--*100@BBDFHG?@CDHD=ADD;<J>DBFCABB223+*(03>677;9:=?,E9.F0<,4>=EBD?<;;557MF>B:?@===;>E<EB:://017+-+51:---264-,::;<<;;948050.//2353=--;>>=BGDADDCC>:;9>>><::00447774-;/=>:0-.++*$)&&$$#$$&%(-56732,16(&.1744=:<448332<8:=44.;F@;88.=559>DB?@:?=>CBBCEC6'*3&(%%%#(8<<<;1B34)),24=7@B>7E6JH=?A>:==::9440-.0.?ADB??8'(7600',9>5@D<&&.<>F@@9633'%$9AA?A5=EEMD>EB?970/1467<>>@EC?H>?@@<=@:@785:473:966:A?)CBA?+%%&$'24843.)(0-./0*$&#&&/01230#$3'6943('02)+$19<;>;2.138832/13?@;67951>>==;:5531$#$$$##%',,&%%$)(/%8,)'%&&26==8>AC@&(.85,-024;;??=A?<43752>@@E??%)-<A=44?>IPF:@1418CBC?HD>@?8A@D?;.;/*'//3@FA;37,3DD;<005*$%%#$%&/:9:98?<;9+-*()),)(89<79+00046=;*=>=:6/>951',&'$%$%+29<?;<=,2287178=@==322?996-.38/&)&,00,-&*++)$$&++.4',53A=<-@@BFFH>8CC@?>=43460*&(%(,-6-A>=A@HE16@AA8;6,74-=A<:;;C>593):8<@@;@8DA:=AD8<><35*%-/0EE=?CHHB=?04=D?>F2A>AA=5>=50-DDCBBC:6/..<@?@A96;55/&%4+1*+&',&#$$$/62*&0%$$+1(*$&)&'$+&$&'('$%##%%%$$$$#,211&%(&)-(#%''%%056,6@>B>555;8:0?:.**>8:@C?ACBE8;<;88;7E??;4;>D>?89>;5E89-2G@1)'(1.63<:5:<;9.&',/+(::DBEB65>AA)*,8,'&&<;@=<7567/02:22B;>BA434..')*'(0)8;5A=%%<55@DB@G>?A<9>><:;AB@F878=?==??50:-',''(#$/)%&&%#$,//245',+)*%//37@<H88=ACA?<<?@<=>8$$(,8678CGOH<=D>5BAPHIGHEEB@;>>4**,0162..,329BI9<<??@B<--5-+0.+'$*.&'+%%%/;<=DA%8(((;<477$937020;E?A@=<>;=@?E2:AD@A??789>AFD@;K7794%%&17&07@'@4:CDEE>@;E9=79A8<=>7=?<=CC*1%.BG=@:;GCE@B?;93@BH5258954A=B==@:@?=?BGD??HG777=<BEDBEBH6=<<<ABBBHE66C??;=HGA@CCDB7991+,177@;>98458<=;==??<;:$8/4446,)'*,...-695)'+6565729;3*0*,%7551,+*,()*)999117($:4>94444559>=@A@1+*')5;?;9((<<@CB<:::=$&&,.366546:=@BBBH@@?@@<':59?9?%>AAABCD??:/16AB><06<===9C<=5=::4-21<>?@=;BCMDFLPCDAB??<>==;;857679=;<A@CACADCA:,(

I made the primers in the above sequence in bold to show that actually they are represented where they should be and are of a fairly high quality. 

After running Pychopper it becomes this (from the full_length_output files):
@1032:1186|93972a90-a05e-49a2-b236-f0c97e9360d6 runid=42615ab958d88032e437976a4c7d836ed71976b3 sampleid=RK_CH2222 read=21915 ch=387 start_time=2019-12-04T00:31:34Z strand=-
AATGTTAAGACCTTACATTTCAACAACATGTTACAGGTATGGCCACAAACAAGTTACTATGAAGTAAGTCAGAATACTTTTTGCAGTGCATTAAATACATATGCTTATTCACATCGCTTGTCCTGCAGTCAACTGTAACCTTAACTCAATCATC
+
.9;<:5:<36.1(')1@G2-98E5;>98?>D>;4;??E7;88;<;8EBCA?C@:8>**.:?0:8;555>B>@6,650%%''%#(-)&(%&112,#$$$$%%%##%$'('&$&+$'&)&$*(1+$$%0&*26/$$$#&,'&+*1+4%&/55;69A

So Pychopper seems to have picked sequences in the reverse complement orientation as the primers. To show how this presented I have segmented the input sequence below to show where the Pychopper sequence fits in it. 

[section before pychopper sequence]
CAGTGTACTTCGTTCGGTTACGTATTGCTTGGATTGATATAGTAATACGACTCACTATAGAGTGTGAGGCGAGCCGTCGAGCGGAGCAGGTCGCTGGTGCGCACCGTGCAGCCGTTAGCTCCACCGCACCCCGCAGCCGGGCCGAGCCACCATGGCTGATCAACTGACAGAAGAGCAGATTGCAGAATTCAAAAGAAGCTTTTTCACTATTTGACAAGGATGGTGATGGTACTATAACTACAAAGGAGTTGGGGACTGTGATGAGATCACTTGGTCAGAACCCCACAGAAGCAGAATTACAGGACATGATCAATGAAGTAGACGCTGATGGCAATGGCACAATTGACTTCCCAGAGTTTCTGACAATGATATGTAAGAAAAATGAAAAAGATACAGATAGCGAAGAAGAAATTAGAGAAGCGTTCCGTGTGTTTGACAAGGATAATTAATGGTTACATTAGTGCTGCAGAACTTCGTCATGTGATGACAAATCTTGGGGAGAAGCTAACAACAGATGAAGAAGTTGATGAAATGATTAGGAAGCAGACATTGATGGTGATGGTCAAGTAAACTATGAAGAGTTTATTGCAAATGACAGCGAAGTAGAAGACGTTGCAGAATGTGTTAAATTTCTTGTACAAAATTGTTTATTTGCCTTTTCTCTGCTGTACTTATCATGAGGTTTCACTTACTGTCAAAAGAATATGTATAGTAATTAGAAGGCCATTCCTCCATGTTTTTCTCCTTTATCTTACTGCCATTGTTACGATTTTTGGAAAATTGATCATGCTCAAATGTTGCATGTGGCTTACTCTGGATATTTAAGCCCTTCTGCACATCAATGTTAGATGGAGGTTGGTAAAATGAGGAACATCTGGATTGTTTAAAATAACTTTCTCTAGAAGACTTAGGTATGACTAGTGTAAGCAAGTTACGTAAAGTAAGTTAGGTTTTACCATGCACATTAGCAGTTCCTTATTTAAAGCGAGATGCTGACCTAGTTTTCCAGTGCGTAAGTTTATTCTGCTTTTT

[rev comp of pychopper result]
GATGATTGAGTTAAGGTTACAGTTGACTGCAGGACAAGCGATGTGAATAAGCATATGTATTTAATGCACTGCAAAAAGTATTCTGACTTACTTCATAGTAACTTGTTTGTGGCCATACCTGTAACATGTTGTTGAAATGTAAGGTCTTAACATT

[section after pychopper sequence]
GTGGACGATTGACAGTCAACAATATGAATCTTAAAGTTGCACTAATGCAAAACGGTGTATTATCCAGGTACTCGTACACAATTTTTGTACTGCTGGTCACCTTTACTGAAAACCTTTTCTCCTCTTGTTACTATGCTTTTTAAACTTTGTTTAGCCACTTATTTCAAAAAAAAAAATCTGCTTATGGCACGATTTGCCTCAAATCCATTCAGATTGTATATTGTTTTCCAATAAAAATTACAATTTACCCATACTGTTCAATGTATCCTTGAATTATTTACAGGATTTGTTCAATACAGTTGCTGCTCTGTGTTTTCCAGTATGTAGCAGTTTGATTTGCTTATGCGATGGATTGGCTGTCTTAAGAGCTTGGAAGGTGAAATCTTAGACCGTAAACTCTGGCCCTTTATTAGTATTGTTGACTTGAAGAAGCTTTCTTTAGTAGTTTAAATGTATTTTACTGATCTTGTGGTAGACTTGGTGTAATATACTTACCATAGTGACTGGCTATGCCCACTATCTGTGGTATTGTGAACTGGATGTTGACCTAGTTCCAATAGTTGACCTAAAATTAAAATTCCTTGTTCAGACAACTAAAAAAAAAAAAAAAAAAAACGCCTGAGAAGCAATACGTA

So this seems like a strange case where Pychopper did not recognize the more obvious primer sequences. This has created transcript models in the opposite strand which are also truncated making them difficult to filter out post-mapping due to the possibility of antisense lncRNA. 

I am still looking into how often this happens but it has definitely created hundreds of false anti-sense genes in my annotation. 

Is there some parameter that I should be using to deal with this? 
Or could Pychopper incorporate an additional algorithm that makes sure the primers are located where they should be with respect to the ends of the reads (I am not talking about the cases where they get funneled into the rescue reads). 

Also I think it would be useful if Pychopper could also use the Y-adapter sequences as well for identifying the primers. 

Thank you,
Richard

**Comment by bsipos** [comment]
Please provide  more detailed information about how did you run pychopper on this dataset!

**Comment by GenomeRIK** [comment]
Hi Botond,

I ran Pychopper with the following command:
python cdna_classifier.py -b primers_teloprime_ont.fa -m edlib -r report_1.pdf -u unclassified_1.fq -w rescued_1.fq fastq_runid_42615ab958d88032e437976a4c7d836ed71976b3_6_3.fastq full_length_output_1.fq


This is the input file with the read:
[fastq_runid_42615ab958d88032e437976a4c7d836ed71976b3_6_3.fastq.gz](https://github.com/nanoporetech/pychopper/files/4281445/fastq_runid_42615ab958d88032e437976a4c7d836ed71976b3_6_3.fastq.gz)

Thank you,
Richard

**Comment by bsipos** [comment]
Could you please post here the primers_teloprime_ont.fa as well?

**Comment by GenomeRIK** [comment]
I posted these already in the original post:
The input primer/adapter sequences are:

SSP
TGGATTGATATGTAATACGACTCACTATAG
VNP
TCTCAGGCGTTTTTTTTTTTTTTTTTT

**Comment by bsipos** [comment]
Sure, but I just wanted to make sure that the primer input was properly formatted fasta.

**Comment by GenomeRIK** [comment]
I tried different orientations of the primer sequences and the one above is what provided what seemed to be the correct performance with around 70% pass rate.

**Comment by GenomeRIK** [comment]
OK here is the primer file. I had to change the extension to "txt" because github does not accept the "fa" extension. 

[primers_teloprime_ont.txt](https://github.com/nanoporetech/pychopper/files/4281558/primers_teloprime_ont.txt)

**Comment by bsipos** [comment]
I had a look and the issue seems to be that you have included reads in the input which have mean quality less than 7 (fail reads). These are essentially junk reads which will confuse the parameter tuning (but not enough that pychopper complains about it).
Please run `seqkit seq -Q 7 input.fq > output.fq` and run pychopper on the output. It seems to me that it gives decent results, despite the custom VNP primer being quite short.
Regarding the Y adapter: the profile HMMs trained on the primers from the ONT kits give good results, hence I don't see the reason for including them in the search (especially that they might not be fully sequenced). However, if you use custom primers feel free to include extra bits flanking the primers for potentially increasing the performance.

Best,
Botond

**Comment by GenomeRIK** [comment]
Hi Botond,

Ok I tried running seqkit on that file and the Pychopper result seems to be good for that read now. However, I am now going to process all of the data again to see if I can find any more instances of the truncation/mis-orientation. 

So I didn't realize that poor quality reads would affect Pychopper. I am guessing Pychopper is creating hmm models based on all the reads submitted?

If this is true, is it better to concatenate all the fastq files after seqkit prior to inputting to Pychopper to build better HMM models for the primers? 

So run all data in the same file as opposed to keeping them split up as in the fast5 outputs from sequencing. 

Thank you,
Richard

**Comment by bsipos** [comment]
In the "edlib" mode pychopper does not use profile HMMs. However, you can build them using the hammerpede pipeline (https://github.com/nanoporetech/hammerpede). Using the hmmer backend might lead to slightly better performance.
Also, I would advise concatenating all fastq records with Q > 7 before running pychopper as the parameter tuning uses a random sample of input reads which should be at least 10k (and much smaller than the whole dataset).

Best,
Botond

**Comment by GenomeRIK** [comment]
Hi Botond,

Ok I am concatenating but I was wondering about you comment of "and much smaller than the whole dataset". How much smaller? 

What would you say is the minimum number of reads (in the dataset)?

Also is there a significant gain to increasing beyond that point?

For instance, if I get more reads from another sequencing run, does it make sense to redo all of the reads from all of the runs together? Or is it ok to just process the new run by itself?

Thank you!
Richard

**Comment by bsipos** [comment]
I would not worry too much about it really unless you have let's say less than 30k reads in your input.
Also, you can always disable tuning bys setting -Y 0 and -q to something reasonable. What is important is that always check the plot of the parameter tuning and become suspicious if the curve is bimodal or the maximum is at the boundary.
