### ISSUE TITLE
some improvement about load the input data

### ISSUE THREAD

**Issue by huangziyan11111** [nanoporetech/pychopper#28]
Since the data size of reads is big, I think maybe you could add some function to support the "*.gz" format of input reads and support standard output as input, so the following codes can be run:

cdna_classifier.py reads_input.fq.gz reads_full_length.fq -t 12 -w rescued.fq -u unclassified.fq -S stats.txt

zcat reads_input.fq.gz|...{some processes}...| cdna_classifier.py - reads_full_length.fq -t 12 -w rescued.fq -u unclassified.fq -S stats.txt

**Comment by bsipos** [comment]
The script needs to do a first pass on the file to count the number of records. Hence input from pipes cannot be supported.
