### ISSUE TITLE
question about the primer sequence

### ISSUE THREAD

**Issue by huangziyan11111** [nanoporetech/pychopper#31]
Hi, I found the default primer sequence (cDNA_SSP_VNP.fas) you use is like this:
>VNP
ACTTGCCTGTCGCTCTATCTTCTTTTTTTTT
>SSP
TTTCTGTTGGTGCTGATATTGCTGGG

However, the Oxford Nanopore universal tag is:
5’-TTTCTGTTGGTGCTGATATTGC-3’ for forward primers
5’-ACTTGCCTGTCGCTCTATCTTC-3’ for reverse primers

See that your primer sequences contain the Oxford Nanopore universal tag. Is it right to have more sequence or just use the Oxford Nanopore universal tag?

**Comment by bsipos** [comment]
The primers are actually are not used in the default profile HMM mode. The "universal tags" are used for  PCR, but these primers are based on the reverse transcription and strand switching primers. I advise do not to change them unless you are using custom oligos.
