### ISSUE TITLE
Parasail error

### ISSUE THREAD

**Issue by cnk113** [nanoporetech/pychopper#33]
Hello,

I've been trying to run the mode with parasail but I keep getting this parasail error.
```python: src/memory.c:245: parasail_result_new_trace: Assertion `b > 0' failed.
Aborted (core dumped)```
I also get this error running hammerpede.
I'm looking at the parasail code and it looks like an input isn't valid?

**Comment by bsipos** [comment]
Did you install pychopper and all dependencies using condo? If not, I suggest you do so and try again.

Botond

**Comment by cnk113** [comment]
I previously was using it in a conda environment, but I went ahead and installed outside using conda, but it gives me a different error
```malloc_consolidate(): invalid chunk size```
Hammerpede still has the original error.

**Comment by bsipos** [comment]
Well, this is a parasail error and you should report it to the parasail developers. Something must be unusual though with your environment.

**Comment by cnk113** [comment]
I also noticed that when I used fastq input into hammerpede it doesn't give me that assertion error, but when I input fasta it does. Could this be a formatting error?
