### ISSUE TITLE
WARNING: No reverse complement for U found, returning argument

### ISSUE THREAD

**Issue by yazuo0204** [nanoporetech/pychopper#34]
Hi, 

I used a direct RNA sequence which filtered by NanoFilt for test, but it gave me millions of warnings. 
![image](https://user-images.githubusercontent.com/47863838/81533396-b3424c00-9398-11ea-8161-28aef64f4f34.png)
Then when I looked in to the full_length.pdf, it presents that most of the reads is unusable. 
This raw data looks fine in other Software test, do I need to modify it before running pychopper? 
![image](https://user-images.githubusercontent.com/47863838/81533565-fe5c5f00-9398-11ea-850c-5fded0f25e46.png)

Thank you !

**Comment by bsipos** [comment]
There is no reason to use pychopper on direct RNA reads as they do not have the primers attached by chemistry. Hence pychopper is not prepared to take RNA sequences containing Us.
