### ISSUE TITLE
customised primer configuration

### ISSUE THREAD

**Issue by ozgegizlenci** [nanoporetech/pychopper#35]
Hello,

I was trying to use pychopper for the primers I designed in my cDNA sequencing with single end barcoded primers. I am trying to understand the configuration file and what it indicates since I was not able to see an explanation about it. 
'Where the contents of primer_config.txt looks like +:MySSP,-MyVNP|-:MyVNP,-MySSP.'
I would assume the + or - indicates the direction of the primers during the nanopore sequencing of each strand. 

Could you please elaborate on it? 
Thank you
Ozge

**Comment by bsipos** [comment]
Hello,

Indeed + and -  before the colon indicate the direction of the sequencing of the read. The - in -MyVNP indicates that the end of the sequence contains the reverse complement of "MyVNP".
Also, please remember that the custom primer functionality only works with the edlib backend (unless you train profile HMMs).

Botond
