### ISSUE TITLE
SyntaxError when running make test

### ISSUE THREAD

**Issue by JoshLoecker** [nanoporetech/pychopper#37]
Hello, I am experiencing a syntax error when running `make test` on pychopper. The error is found on line 56 in hmmer_backend.py. The following link contains a pastebin to the error output. Do you know of any method to fix this?

Thanks!

[https://pastebin.com/g1zju2Xs](https://pastebin.com/g1zju2Xs)

**Comment by eamanu** [comment]
Seems to be that use a `cmp` command, but I'm not sure if this is a missing dependency?

**Comment by eamanu** [comment]
Sorry for my noise is default POSIX

**Comment by bsipos** [comment]
It seems that you do not have the hmmer dependency installed. Please install pychopper from biconda and try again.
