### ISSUE TITLE
Analyzing pcr cDNA barcoded sequencing data using pychopper

### ISSUE THREAD

**Issue by Kyung-TaeLee** [nanoporetech/pychopper#38]
Hi, I have recently sequenced RNA samples from drosophila using PCB109 Nanopore kit (PCR cDNA barcoded kit).

At first, I ran guppy basecalling with "--trim" option to trim off the barcode sequences. When I ran pychopper on these reads, most of the reads were unclassified. I did some research and found out the feed saying, if you trim off the barcode sequences, "VNP" and "SSP" primers will also be removed. It would be great if you can confirm that this is true. And if it is, should I run basecalling without "--trim" option? If I do that, how can I trim off the (barcode + primer) sequences from the read since I am worried that these sequences will interfere with proper alignment of the read due to the fact they are not the sequences from genome.

Second, as far as I understand, pychopper re-orient reads with orientation information added in the output ("+" or "-"). Does this re-orientation means that it orients reads to match the actual RNA molecule?
![Nanopore cDNA PCR2](https://user-images.githubusercontent.com/67738841/86479912-f9f46700-bd87-11ea-86f5-f03014eae15d.PNG)
For example, when cDNA library is generated, dsDNA with motor protein at one end of each DNA strand will be generated. If first-strand cDNA, which has polyT at the end and is bottom strand in the picture above ,is sequenced (I am not sure which strand of dsDNA is more frequently sequenced. Are they randomly sequenced?), the sequenced read is the reverse-complement of actual RNA molecule. Then, does the re-orientation of the read reverse-complement this read to match the actual RNA molecule? and does the strand information added at the end of read in output from pychopper means the relative strand of the read to actual RNA molecule? 
If my assumption is correct, does it means that all reads classified and re-oriented by pychopper are sequences that match the actual RNA molecule?

Thank you reading my writing and sorry for asking too many questions... but hope you can give me clear answers to this. Thank you again for providing such a wonderful tool!

**Comment by bsipos** [comment]
Hello!

Yes, please run guppy without the `--trim` option to preserve the primers detected by pychopper. These will be trimmed of in the output unless you specify the `-p` option.
Also, your assumptions about the re-orientation are correct, hence you can consider the output of pychopper "stranded".

Botond
