### ISSUE TITLE
Workflow from base calling to pychopper?

### ISSUE THREAD

**Issue by cgjosephlee** [nanoporetech/pychopper#4]
I have base called using albacore and the primer/adaptor/barcode are removed after base calling. So if I want to run the pychopper and pinfish pipeline, should I base called with keeping all the primer/adaptor/barcode sequences? and remove the primer/adaptor/barcode after running pychopper?

ps. I don't see a variable in albacore is to keep the primer/adaptor/barcode, would you suggest using another base caller?

**Comment by bsipos** [comment]
Hello,

Albacore will only perform barcode demultiplexing if the `--barcoding` option is specified. Whatever options you are using, albacore will not remove the reverse transcription primers. Pychopper is looking for those, hence you can use it after basecalling with albacore,

Regards,
Botond
