### ISSUE TITLE
pychopper length distribution in report doesn't match fastqc or nanostats 

### ISSUE THREAD

**Issue by kneubehl** [nanoporetech/pychopper#40]
Hi there,
I am using data from SQK-PCS109 prefiltered for length (100bp) and quality score (>7) using NanoFilt which I ran on pychopperv2 (cdna_classifier.py -S stats.report -r report.pdf -u unclassified.fq -w rescued.fq input_reads.fq full_length_output.fq). I took a look at the 'Log10 length distribution of trimmed away sequences' plot in the report and it looked ok with a great peak at ~1.5kb and about 85% of the reads were classified 'primers found'. However, both fastqc and NanoStats show a different story in the full_length_output.fq). Fastqc's length distribution shows a peak around 500bp and NanoStats indicates a mean read length of 514bp and a median of 465bp. Also there are now reads with a quality score below 5 (prefiltered input reads had a quality score >7). What would be the cause of the discrepancy? Am I missing something silly here? I have attached the pychopper report pdf and the nanostats report and a screenshot of fastqc read length distribution, all on the full_length_output.fq of pychopperv2. 
[full_length_cDNA.txt](https://github.com/nanoporetech/pychopper/files/4950010/full_length_cDNA.txt)
[report.pdf](https://github.com/nanoporetech/pychopper/files/4950011/report.pdf)

![Screenshot from 2020-07-20 15-48-59](https://user-images.githubusercontent.com/58899964/87985044-93b65680-caa0-11ea-970f-c0cbc5b8fbad.png)

Thanks!

**Comment by GenomeRIK** [comment]
Hello, I looked at the report.pdf file and there are no plots for the length distribution of the accepted reads. The plot on the last page is for the trimmed away sequences and is given in log10. So that is just showing that most of the trimmed away sequence were less than 50bp. 

Cheers,
Richard

**Comment by kneubehl** [comment]
Silly me. Thanks for the info!
