### ISSUE TITLE
Only reverse reads are classified

### ISSUE THREAD

**Issue by illarionovaanastasia** [nanoporetech/pychopper#41]
Hello! 

I am working on PCR free cDNA sequencing data (DCS109) and I would like to perform a quantification analysis. 
I have run guppy (v3.6.1) in a default mode and pychopper (last release) was able to classify only 27% of reads (1:1 both strands). 
Afterwards, I figured out that in a default mode guppy trims out adapters and primers, so I have rerun the basecalling with a --trim_strategy none flag, and pychopper classified 46%, however, all of the classified reads were annotated as reverse stranded.  I have attached the [score file](https://github.com/nanoporetech/pychopper/files/5193216/pychopper_scores.bed.gz) obtained from the -A flag with first 500K entries and a [pdf report](https://github.com/nanoporetech/pychopper/files/5193221/pychopper_edlib_q7_report2.pdf) for the latter case.

I would really appreciate any advice of how to check wherever this is a problem of the analysis or with the actual data.

**Comment by bsipos** [comment]
Hello! 

To further diagnose the problem could you please run pychopper with the `-x DCS109` option on the previously unclassified reads?

**Comment by hugs314** [comment]
I had a similar problem, but it was a little different.
The oriented reads came from The + and - strands in a roughly 1:1 when default mode.
The oriented reads came from - strands with -x DCS109
