### ISSUE TITLE
How do I make a custom_primer.fa file?

### ISSUE THREAD

**Issue by HappyCondaUser** [nanoporetech/pychopper#43]
I used sequence specific primer to synthesize cDNA and made library using PCR cDNA barcoding kit.  I would like to use pychopper to rescue the full length cDNA.  What do I need to put in the custom_primer.fa file? This is one of the primer I used:  ACTTGCCTGTCGCTCTATCTTCTACTGTGCAGTGTATGACCAG.

**Comment by bsipos** [comment]
Hello!

The custom primer file should look similar to this [fasta file](https://github.com/nanoporetech/pychopper/blob/master/pychopper/primer_data/PCS110_primers.fas). Note that specifying a custom primer file will only have an effect if you also specify using the edlib method via `-m edlib`.
