### ISSUE TITLE
Rescued reads

### ISSUE THREAD

**Issue by ines-batista** [nanoporetech/pychopper#47]
Hi there!

I'm using pychopper through the [pipeline-nanopore-ref-isoforms](https://github.com/nanoporetech/pipeline-nanopore-ref-isoforms) and I was wondering what exactly the rescued reads would be.

I read all of the available documentation, but I'm still not sure if I got it.
Could you explain that to me?

Thanks in advance,
Inês B.

**Comment by bsipos** [comment]
Hello! Please have a look at the pychopper [README](https://github.com/nanoporetech/pychopper) which describes the process of rescuing fusion reads.
