### ISSUE TITLE
question for input of the  pychopper 

### ISSUE THREAD

**Issue by hmyh1202** [nanoporetech/pychopper#48]
Hello, 

   I am new for preparing a input file of fastq format. Now I have download an ONT full-length transcript fastq file. But I do not know how was it generated. If the  original fastq file can as a input file for  pychopper ? Or the original file should do some filter and qualitification ?

Thanks!

**Comment by bsipos** [comment]
Could you please clarify your issue? Is the file you downloaded already processed by pychopper?

**Comment by philres** [comment]
Hi. I'm closing this issue since it has bee a while. Please reopen if you are still having problems running pychopper.

Thanks,
Philipp
