### ISSUE TITLE
Command（make test） execution failed

### ISSUE THREAD

**Issue by wlhCNU** [nanoporetech/pychopper#5]
Hi，

     I encountered some problems in  execute the  command “make test”.  The error message is as follows, what might have caused the error ?
Thank you

lihui

###########################make test   log###################################
make test
py.test
============================================================= test session starts ==============================================================
platform linux -- Python 3.6.6, pytest-4.0.1, py-1.7.0, pluggy-0.8.0
rootdir: /export/wlh/01.software/pychopper, inifile: pytest.ini
plugins: remotedata-0.3.1, openfiles-0.3.1
collected 3 items                                                                                                                              

pychopper/tests/test_detector.py ..                                                                                                      [ 66%]
pychopper/tests/test_integration.py F                                                                                                    [100%]

=================================================================== FAILURES ===================================================================
_______________________________________________________ TestIntegration.testIntegration ________________________________________________________

self = <pychopper.tests.test_integration.TestIntegration testMethod=testIntegration>

    def testIntegration(self):
        """ Integration test. """
        base = path.dirname(__file__)
        pkg_base = path.dirname(path.dirname(base))
        test_base = path.join(base, 'data')
    
        cdna_classifier = path.join(pkg_base, 'scripts', 'cdna_classifier.py')
        barcodes = path.join(test_base, 'barcodes.fas')
        input_fasta = path.join(test_base, 'ref.fas')
        output_fasta = path.join(test_base, 'test_output.fas')
        expected_output = path.join(test_base, 'expected_output.fas')
    
        subprocess.call([cdna_classifier, '-i', 'fasta', '-s', '95.0', '-b', barcodes, input_fasta, output_fasta])
        retval = subprocess.call(['cmp', output_fasta, expected_output])
>       self.assertEqual(retval, 0)
E       AssertionError: 2 != 0

pychopper/tests/test_integration.py:23: AssertionError
------------------------------------------------------------- Captured stderr call -------------------------------------------------------------
Traceback (most recent call last):
  File "/export/wlh/01.software/pychopper/scripts/cdna_classifier.py", line 9, in <module>
    from pychopper import chopper
  File "/export/wlh/01.software/pychopper/pychopper/chopper.py", line 6, in <module>
    from pychopper import seq_detect
  File "/export/wlh/01.software/pychopper/pychopper/seq_detect.py", line 5, in <module>
    import parasail
  File "/export/wlh/01.software/anaconda3/lib/python3.6/site-packages/parasail-1.1.12-py3.6.egg/parasail/__init__.py", line 30, in <module>
    _lib = ctypes.CDLL(_libname)
  File "/export//wlh/01.software/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libparasail.so: cannot open shared object file: No such file or directory
cmp: /export//wlh/01.software/pychopper/pychopper/tests/data/test_output.fas: No such file or directory
===================================================== 1 failed, 2 passed in 73.85 seconds ======================================================
make: *** [test] Error 1
################################################################################

**Comment by bsipos** [comment]
Hello,

It seems that the [parasail l](https://github.com/jeffdaily/parasail-python) library (which is a dependency of pychopper) is not installed properly. Please try to reinstall it separately or install it from source.

**Comment by SziKayLeung** [comment]
Hello @bsipos 

I had the exact same problem and re-installation of parasail semi-worked. However I'm not encountering the following error with "make test"

Any guidance would be greatly appreciated - thank you!

`========================================================================= test session starts ==========================================================================
platform linux -- Python 3.6.5, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
rootdir: /gpfs/mrc0/projects/Research_Project-MRC148213/sl693/softwares/pychopper, inifile: pytest.ini, testpaths: pychopper
collected 3 items

pychopper/tests/test_detector.py ..                                                                                                                              [ 66%]
pychopper/tests/test_integration.py F                                                                                                                            [100%]

=============================================================================== FAILURES ===============================================================================
___________________________________________________________________ TestIntegration.testIntegration ____________________________________________________________________

self = <pychopper.tests.test_integration.TestIntegration testMethod=testIntegration>

    def testIntegration(self):
        """ Integration test. """
        base = path.dirname(__file__)
        pkg_base = path.dirname(path.dirname(base))
        test_base = path.join(base, 'data')

        cdna_classifier = path.join(pkg_base, 'scripts', 'cdna_classifier.py')
        barcodes = path.join(test_base, 'barcodes.fas')
        input_fasta = path.join(test_base, 'ref.fas')
        output_fasta = path.join(test_base, 'test_output.fas')
        expected_output = path.join(test_base, 'expected_output.fas')

        subprocess.call([cdna_classifier, '-i', 'fasta', '-s', '95.0', '-b', barcodes, input_fasta, output_fasta])
        retval = subprocess.call(['cmp', output_fasta, expected_output])
>       self.assertEqual(retval, 0)
E       AssertionError: 1 != 0

pychopper/tests/test_integration.py:23: AssertionError
------------------------------------------------------------------------- Captured stdout call -------------------------------------------------------------------------
/gpfs/mrc0/projects/Research_Project-MRC148213/sl693/softwares/pychopper/pychopper/tests/data/test_output.fas /gpfs/mrc0/projects/Research_Project-MRC148213/sl693/softwares/pychopper/pychopper/tests/data/expected_output.fas differ: char 11, line 1
------------------------------------------------------------------------- Captured stderr call -------------------------------------------------------------------------
 98%|#########8| 4628/4703 [00:00<00:00, 516132.81it/s]
================================================================= 1 failed, 2 passed in 12.06 seconds ==================================================================
make: *** [test] Error 1
`
