### ISSUE TITLE
can pychopper be used with SQK-DCS109 kit?

### ISSUE THREAD

**Issue by pcantalupo** [nanoporetech/pychopper#50]
Hello,
I'm working with a client who used the SQK-DCS109 kit for sequencing. Can pychopper be used for this kit? Do I have to supply the primer sequences or will the [default primers](https://github.com/nanoporetech/pychopper/blob/master/pychopper/primer_data/cDNA_SSP_VNP.fas) suffice?

Thank you

**Comment by pcantalupo** [comment]
Also, if I use the `-b custom_primers.fas` parameter, does that effectively replace the  [default primers](https://github.com/nanoporetech/pychopper/blob/master/pychopper/primer_data/cDNA_SSP_VNP.fas) file with the one that I'm supplying with the `-b` param?

**Comment by bsipos** [comment]
Hello! Yes, pychopper will work with SQK-DCS109 with default primers. The `-b` option will override the primers used, but only for the -m edlib method. Also, you might want to run the `-x DCS109` "rescue mode" on the unclassified reads.
