### ISSUE TITLE
Protocol-specific read rescue for DCS109 (-x parameter) didn't seem to work

### ISSUE THREAD

**Issue by pcantalupo** [nanoporetech/pychopper#51]
Hello,  I tried running with `-x DCS109` on my unclassified reads from previous pychopper run but I got the same number of unclassified reads as were input to pychopper. Here is the command line:

`cdna_classifier.py -m edlib -b custom_primers.fa -c primer_config.txt -r report.pdf -S statistics.tsv -A aln_hits.bed -x DCS109 -u unclassifiedDCS109rescue.fq -l length_fail.fq -w rescued.fq -K minqual_fail.fq unclassified.fq fulllength.fq > py.out 2>&1`

and here are the number of fastq seqs in each fastq output file:

```
$ ~/bin/numfastq.pl *.fq
unclassified.fq	235013
rescued.fq	0
length_fail.fq	0
unclassifiedDCS109rescue.fq	235013
fulllength.fq	0
minqual_fail.fq	0
```

Here is the pychopper output:
```
$ cat py.out 
Using kit: PCS109
Configurations to consider: "-:VNP,-VNP"
Counting fastq records in input file: unclassified.fq
Total fastq records in input file: 235013
Tuning the cutoff parameter (q) on 9996 sampled reads (4.3%) passing quality filters (Q >= 7.0).
Optimizing over 30 cutoff values.
100%|██████████| 30/30 [01:50<00:00,  3.67s/it]
Best cutoff (q) value is 0 with 0% of the reads classified.
Processing the whole dataset using a batch size of 29376:
100%|██████████| 235013/235013 [01:23<00:00, 2830.44it/s]
Finished processing file: unclassified.fq
Input reads failing mean quality filter (Q < 7.0): 0 (0.00%)
Output fragments failing length filter (length < 50): 0
-----------------------------------
Reads with two primers:	0.00%
Rescued reads:		0.00%
Unusable reads:		100.00%
-----------------------------------
```

I wonder if the problem is that I'm using a modified VNP sequence (SSP is exactly the same as pychopper's SSP) without the poly T tail since my client created her own VNP using a different ending that is specific to the 3' end of a virus. I noticed that in the pychopper output that the configurations to consider are -:VNP,-VNP.  This is different that I expected since I'm not using `VNP` but rather my custom `MyVNP` sequence: 

```
$ cat custom_primers.fa 
>MyVNP
ACTTGCCTGTCGCTCTATCTTC
>SSP
TTTCTGTTGGTGCTGATATTGCTGGG
```

My primer config file looks like this:
```
$ cat primer_config.txt 
+:SSP,-MyVNP|-:MyVNP,-SSP
```

I can clearly find thousands of sequences that have a perfect match to both SSP and MyVNP in the same sequence. If I search for just the SSP or MyVNP sequence separately, I find many thousands more sequences that contain a primer.

```
$ grep -E 'TTTCTGTTGGTGCTGATATTGCTGGG.*GAAGATAGAGCGACAGGCAAGT' unclassifiedDCS109rescue.fq | wc -l
5595
$ grep -E 'ACTTGCCTGTCGCTCTATCTTC.*CCCAGCAATATCAGCACCAACAGAAA' unclassifiedDCS109rescue.fq | wc -l
1178
```

Am I running pychopper correctly?  Thank you,

**Comment by bsipos** [comment]
Hello! Please call your VNP sequence `VNP` instead of `MyVNP`. Also, in order to run the `-x DCS109` mode, first run pychopper on the unclassified reads in the default mode. Then run the rescue mode on the unclassified reads from the first output.
