### ISSUE TITLE
Any chance of getting pychopper to accept gzipped fastq as input?

### ISSUE THREAD

**Issue by oneillkza** [nanoporetech/pychopper#53]
We keep all our fastqs gzipped by default, and guppy now has an option to output them already-zipped. Would it be possible to get pychopper to accept these?

**Comment by oneillkza** [comment]
Or piped input, so it could be run via zcat?

**Comment by philres** [comment]
Hi,

Thanks for bringing this up. Support for gzipped FASTQ files is on my todo list. I agree that would be a very important feature. Piped input is something I was thinking about but the problem with pychopper right now is that it auto tunes one of the parameters by looking at the first few thousand reads in the input file. Thus it has to read those reads twice which makes streaming input a bit more difficult. 

I'm afraid I can't give you a timeline but will keep you posted about progress on those two things.

Thanks,
Philipp

**Comment by philres** [comment]
Hi again,

If you update pychopper using:
```
pip install git+https://github.com/nanoporetech/pychopper.git
```
In your existing (conda) environment you should get v2.6.0 that should support read gzipped inptut files now.

Please let me know in case something doesn't work.

Thanks,
Philipp

**Comment by philres** [comment]
Hi again,

did you have a chance to give the new version a try?

Thanks,
Philipp

**Comment by philres** [comment]
Closing this for now. Please let me know if you have any problems with gzipped inputs.

**Comment by oneillkza** [comment]
Thanks @philres . Sorry for the late reply, but yes, I have had a chance to test this, and it seems to work great, and definitely simplifies the workflow.

I wonder if it would be possible to get streamed output, so it could be piped directly to gzip? Or to get gzipped output as an option?

**Comment by philres** [comment]
Glad to hear that it works. Output to stdout should be in this version
already. Could you please try not specifying an output file? That should
make pychopper write output to stdout so you can stream directly into gzip.

**Comment by oneillkza** [comment]
Oh great! Yep -- that seems to work, and is much more streamlined. Thank you!

**Comment by philres** [comment]
Great, thanks for testing. Will try to get a new release out soon but would
like to get reading from stdin implemented first.
