### ISSUE TITLE
make test issue (macOS)

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/pychopper#6]
I am having trouble with make test, and make docs.

After clone and install in Users/user/pychopper/

make test gives

`tkx292:~ callum$ cd pychopper/
tkx292:pychopper callum$ make test
py.test
make: py.test: No such file or directory
make: *** [test] Error 1`

Also tried installing via pip into miniconda/lib/python3.6/site-packages. Still same problem.

**Comment by bsipos** [comment]
Hi,

Could you please try to install the [pytest](https://pypi.org/project/pytest/) package?

Botond

**Comment by callumparr** [comment]
Ah that did the trick

=============================================================================================== test session starts ================================================================================================
platform darwin -- Python 3.6.5, pytest-4.1.1, py-1.7.0, pluggy-0.8.1
rootdir: /Users/callum/pychopper, inifile: pytest.ini
collected 3 items                                                                                                                                                                                                  

pychopper/tests/test_detector.py ..                                                                                                                                                                          [ 66%]
pychopper/tests/test_integration.py .                                                                                                                                                                        [100%]

============================================================================================ 3 passed in 23.29 seconds =========================================================================

This is the expected outcome?

**Comment by bsipos** [comment]
Yes, pretty much.
