### ISSUE TITLE
Does Pychopper work with the PCS111 PCR cDNA kit?

### ISSUE THREAD

**Issue by bernardo-heberle** [nanoporetech/pychopper#64]
Hi

I have some data generated from the PCS111 PCR cDNA kit and I was wondering if I need to manually input the primers or if Pychopper is already able to handle the primers for this new kit? 

Best,
Bernardo

**Comment by bernardo-heberle** [comment]
@cjw85, I see that your latest commit seems to address this issue. 

If I install the pychopper today with the command `pip install git+https://github.com/nanoporetech/pychopper.git` will I be able to run pychopper using `-k PCS111` and therefore successfully identify, trim, and orient ONT data generated with the new PCS111 kit?

**Comment by nrhorner** [comment]
Hi Bernardo.

using `-k PCS111` should work with the github installation as you've described. There will be conda package released soon also.

Please let me know if you encounter any issues.

Neil

**Comment by bernardo-heberle** [comment]
Great, thank you!
